forecaster/urls.py
from django.urls import path

from forecaster import views


urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.create_forecast, name="new"),
    path("create", views.create, name="create"),
    path("graph-data", views.normal_distribution, name="graph-data"),
    path("recent", views.recent, name="recent"),
]

simple_forecaster/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("forecaster.urls")),
    path("admin/", admin.site.urls),
]

forecaster/models.py
from django.db import models


class Forecast(models.Model):
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    title = models.CharField(max_length=50, default="no title")
    mean = models.DecimalField(decimal_places=1, max_digits=3)
    variance = models.DecimalField(decimal_places=1, max_digits=3)

forecaster/views.py
import numpy as np

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from scipy.stats import norm

from forecaster.models import Forecast


def index(request):
    """The index is the homepage and lists all the stored forecasts and links
    to a new forecast creation page.
    """

    return render(request, "index.html")


def create_forecast(request):
    """The create forecast page has a drawing area to draw probabilistic
    distributions.

    Currently, only the normal distribution is implemented.

    Hitting the delete key undos the last action.

    There is a title field and a save button, which stores the forecast in the
    database.
    """

    return render(request, "new.html")


def create(request):
    if request.method == "POST":
        params = request.POST

        Forecast.objects.create(
            title=params.get("title", "no title"),
            mean=float(params.get("mean", 50)),
            variance=float(params.get("variance", 10)),
        )

        return HttpResponse("success")


def normal_distribution(request):
    params = request.GET

    x = np.linspace(0, 100, 21)
    mean = float(params.get("mean", 50))
    variance = float(params.get("variance", 10))
    data = {
        "labels": x.tolist(),
        "y": (norm.pdf(x, mean, variance) * 100).tolist(),
    }

    return JsonResponse(data=data)


def recent(request):
    forecasts = Forecast.objects.all().order_by("-created")[:10]

    normals = np.ones(shape=[len(forecasts), 21])
    titles = []
    x = np.linspace(0, 100, 21)

    for index, forecast in enumerate(forecasts):
        normals[index] *= (norm.pdf(x, float(forecast.mean), float(forecast.variance)) * 100)
        titles.append(forecast.title)

    data = {
        "labels": x.tolist(),
        "y": normals.tolist(),
        "titles": titles,
    }

    return JsonResponse(data=data)

forecaster/templates/index.html
<!DOCTYPE html>
<html>
    <header>
        <h1>
            Simple Forecaster
        </h1>

        <h3>
            by Austin Nhung
        </h3>
    </header>

    <body>
        <button type="button">
            <a href="{% url 'new' %}">
                Create a new forecast
            </a>
        </button>

        <h2>
            Most recent forecasts...
        </h2>
    </body>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <script type="text/javascript">
        $.ajax({
            method: "GET",
            url: "/recent",
            success: makeGraphs,
        });

        function makeGraphs(data) {
            var charts = {};
            var contexts = {};

            for (var i = 0; i < data.titles.length; i++) {
                document.body.innerHTML += '<div class="graph" style="width: 75%"><h3>' + data.titles[i] + '</h3><canvas id="id_graph_' + i + '"></canvas></div>';
                contexts[i] = document.getElementById("id_graph_" + i);
                charts[i] = new Chart(
                    contexts[i],
                    {
                        type: "line",
                        data: {
                            labels: data.labels,
                            datasets: [{
                                data: data.y[i],
                            }],
                        },
                        options: {
                            elements: {
                                point: {
                                    pointStyle: "line",
                                },
                            },
                            legend: {
                                display: false,
                            },
                            responsive: true,
                        },
                    },
                );
            }
        }
    </script>
</html>

forecaster/templates/new.html
<!DOCTYPE html>
<html>
    <header>
        <h1>
            Create a new forecast
        </h1>
    </header>

    <body>
        <form id="id_form">
            {% csrf_token %}

            <div class="forecastTitle">
                <h2>
                    Give your forecast a title
                </h2>
                <input id="id_title" type="text">
            </div>

            <div class="slider">
                <h3>
                    Mean
                </h3>
                <input id="id_mean" type="range" min="0" max="100" step="0.1" value="50" style="width: 75%;" oninput="id_meanValue.innerText = this.value">
                <p id="id_meanValue">50</p>
            </div>

            <div class="slider">
                <h3>
                    Variance
                </h3>
                <input id="id_variance" type="range" min="0" max="100" step="0.1" value="10" style="width: 75%" oninput="id_varianceValue.innerText = this.value">
                <p id="id_varianceValue">10</p>
            </div>

            {% block content %}
                <div id="id_container" style="width: 75%;">
                    <canvas id="id_graph" data-url="{% url 'graph-data' %}"></canvas>
                </div>
            {% endblock %}

            <button id="id_submitButton" type="submit">
                Submit
            </button>
        </form>

    </body>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <script type="text/javascript">
        $(document).on('submit', '#id_form', function(e) {
            e.preventDefault();

            $.ajax({
                type: 'POST',
                url: 'create',
                data: {
                    title: $('#id_title').val(),
                    mean: $('#id_mean').val(),
                    variance: $('#id_variance').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                },
                success: function() {
                    alert("Successfully created forecast");
                }
            });
        });
    </script>

    <script type="text/javascript">
        var mean = document.getElementById('id_mean');
        var variance = document.getElementById('id_variance');

        mean.addEventListener('change', updateGraph);
        variance.addEventListener('change', updateGraph);

        updateGraph();

        function updateGraph() {
            $.ajax({
                method: "GET",
                url: "/graph-data",
                data: {
                    mean: mean.value,
                    variance: variance.value,
                },
                success: function(data) {
                    const context = document.getElementById("id_graph");
                    const chart = new Chart(
                        context,
                        {
                            type: "line",
                            data: {
                                labels: data.labels,
                                datasets: [{
                                    data: data.y,
                                }],
                            },
                            options: {
                                elements: {
                                    point: {
                                        pointStyle: "line"
                                    }
                                },
                                legend: {
                                    display: false
                                },
                                responsive: true
                            }
                        }
                    )
                }
            });
        }
    </script>

</html>